# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculatie_pb2 as calculatie__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculatie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateProject = channel.stream_stream(
                '/calculatie.CalculationService/CalculateProject',
                request_serializer=calculatie__pb2.CalculatePriceRequest.SerializeToString,
                response_deserializer=calculatie__pb2.ConfirmCalculationResponse.FromString,
                _registered_method=True)
        self.GetProjectCalculations = channel.unary_stream(
                '/calculatie.CalculationService/GetProjectCalculations',
                request_serializer=calculatie__pb2.GetProjectCalculationsRequest.SerializeToString,
                response_deserializer=calculatie__pb2.GetCalculationResponse.FromString,
                _registered_method=True)
        self.GetCalculation = channel.unary_unary(
                '/calculatie.CalculationService/GetCalculation',
                request_serializer=calculatie__pb2.GetCalculationRequest.SerializeToString,
                response_deserializer=calculatie__pb2.GetCalculationResponse.FromString,
                _registered_method=True)
        self.DeleteCalculation = channel.unary_unary(
                '/calculatie.CalculationService/DeleteCalculation',
                request_serializer=calculatie__pb2.DeleteCalculationRequest.SerializeToString,
                response_deserializer=calculatie__pb2.ConfirmCalculationResponse.FromString,
                _registered_method=True)
        self.UpdateCalculation = channel.unary_unary(
                '/calculatie.CalculationService/UpdateCalculation',
                request_serializer=calculatie__pb2.UpdateCalculationRequest.SerializeToString,
                response_deserializer=calculatie__pb2.ConfirmCalculationResponse.FromString,
                _registered_method=True)


class CalculationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateProject(self, request_iterator, context):
        """Calculate the price of different articles for a project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectCalculations(self, request, context):
        """Get all calculations for a project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalculation(self, request, context):
        """Get a calculation by id -> used for updating and deleting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCalculation(self, request, context):
        """Delete a calculation by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCalculation(self, request, context):
        """Update a calculation by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateProject': grpc.stream_stream_rpc_method_handler(
                    servicer.CalculateProject,
                    request_deserializer=calculatie__pb2.CalculatePriceRequest.FromString,
                    response_serializer=calculatie__pb2.ConfirmCalculationResponse.SerializeToString,
            ),
            'GetProjectCalculations': grpc.unary_stream_rpc_method_handler(
                    servicer.GetProjectCalculations,
                    request_deserializer=calculatie__pb2.GetProjectCalculationsRequest.FromString,
                    response_serializer=calculatie__pb2.GetCalculationResponse.SerializeToString,
            ),
            'GetCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalculation,
                    request_deserializer=calculatie__pb2.GetCalculationRequest.FromString,
                    response_serializer=calculatie__pb2.GetCalculationResponse.SerializeToString,
            ),
            'DeleteCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCalculation,
                    request_deserializer=calculatie__pb2.DeleteCalculationRequest.FromString,
                    response_serializer=calculatie__pb2.ConfirmCalculationResponse.SerializeToString,
            ),
            'UpdateCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCalculation,
                    request_deserializer=calculatie__pb2.UpdateCalculationRequest.FromString,
                    response_serializer=calculatie__pb2.ConfirmCalculationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculatie.CalculationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculatie.CalculationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateProject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/calculatie.CalculationService/CalculateProject',
            calculatie__pb2.CalculatePriceRequest.SerializeToString,
            calculatie__pb2.ConfirmCalculationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectCalculations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/calculatie.CalculationService/GetProjectCalculations',
            calculatie__pb2.GetProjectCalculationsRequest.SerializeToString,
            calculatie__pb2.GetCalculationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculatie.CalculationService/GetCalculation',
            calculatie__pb2.GetCalculationRequest.SerializeToString,
            calculatie__pb2.GetCalculationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculatie.CalculationService/DeleteCalculation',
            calculatie__pb2.DeleteCalculationRequest.SerializeToString,
            calculatie__pb2.ConfirmCalculationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculatie.CalculationService/UpdateCalculation',
            calculatie__pb2.UpdateCalculationRequest.SerializeToString,
            calculatie__pb2.ConfirmCalculationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
