# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculatie.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'calculatie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculatie.proto\x12\ncalculatie\"\x80\x01\n\x15\x43\x61lculatePriceRequest\x12!\n\x19\x62uilding_specification_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x02\x12\x16\n\x0eprice_per_unit\x18\x05 \x01(\x02\"P\n\x16\x43\x61lculatePriceResponse\x12!\n\x19\x62uilding_specification_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_price\x18\x02 \x01(\x02\x32s\n\x12\x43\x61lculationService\x12]\n\x10\x43\x61lculateProject\x12!.calculatie.CalculatePriceRequest\x1a\".calculatie.CalculatePriceResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculatie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATEPRICEREQUEST']._serialized_start=33
  _globals['_CALCULATEPRICEREQUEST']._serialized_end=161
  _globals['_CALCULATEPRICERESPONSE']._serialized_start=163
  _globals['_CALCULATEPRICERESPONSE']._serialized_end=243
  _globals['_CALCULATIONSERVICE']._serialized_start=245
  _globals['_CALCULATIONSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
