# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculatie_pb2 as calculatie__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculatie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateProject = channel.stream_stream(
                '/calculatie.CalculationService/CalculateProject',
                request_serializer=calculatie__pb2.CalculatePriceRequest.SerializeToString,
                response_deserializer=calculatie__pb2.CalculatePriceResponse.FromString,
                _registered_method=True)


class CalculationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateProject(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateProject': grpc.stream_stream_rpc_method_handler(
                    servicer.CalculateProject,
                    request_deserializer=calculatie__pb2.CalculatePriceRequest.FromString,
                    response_serializer=calculatie__pb2.CalculatePriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculatie.CalculationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculatie.CalculationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateProject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/calculatie.CalculationService/CalculateProject',
            calculatie__pb2.CalculatePriceRequest.SerializeToString,
            calculatie__pb2.CalculatePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
